export interface Billing {
  id: string;
  name: string;
  date: string;
  type: string;
  amount: string;
  created_by: string;
  users: "all" | string[];
  status: "completed" | "cancelled" | "draft" | "upcoming";
}

export const billings: Billing[] = [
  {
    id: "1",
    name: "Billing Event 1",
    date: "2023-01-01",
    type: "subscription",
    amount: "100.00",
    created_by: "admin",
    users: "all",
    status: "completed",
  },
  {
    id: "2",
    name: "Billing Event 2",
    date: "2023-02-01",
    type: "one-time",
    amount: "200.00",
    created_by: "admin",
    users: ["user1", "user2"],
    status: "upcoming",
  },
  {
    id: "3",
    name: "Billing Event 3",
    date: "2023-03-01",
    type: "subscription",
    amount: "150.00",
    created_by: "user1",
    users: ["user3"],
    status: "draft",
  },
  {
    id: "4",
    name: "Billing Event 4",
    date: "2023-04-01",
    type: "one-time",
    amount: "250.00",
    created_by: "user2",
    users: "all",
    status: "cancelled",
  },
  {
    id: "5",
    name: "Billing Event 5",
    date: "2023-05-01",
    type: "subscription",
    amount: "300.00",
    created_by: "admin",
    users: ["user4", "user5"],
    status: "completed",
  },
  {
    id: "6",
    name: "Billing Event 6",
    date: "2023-06-01",
    type: "one-time",
    amount: "350.00",
    created_by: "user3",
    users: ["user6"],
    status: "upcoming",
  },
  {
    id: "7",
    name: "Billing Event 7",
    date: "2023-07-01",
    type: "subscription",
    amount: "400.00",
    created_by: "admin",
    users: "all",
    status: "draft",
  },
  {
    id: "8",
    name: "Billing Event 8",
    date: "2023-08-01",
    type: "one-time",
    amount: "450.00",
    created_by: "user4",
    users: ["user7", "user8"],
    status: "completed",
  },
  {
    id: "9",
    name: "Billing Event 9",
    date: "2023-09-01",
    type: "subscription",
    amount: "500.00",
    created_by: "user5",
    users: ["user9"],
    status: "cancelled",
  },
  {
    id: "10",
    name: "Billing Event 10",
    date: "2023-10-01",
    type: "one-time",
    amount: "550.00",
    created_by: "admin",
    users: "all",
    status: "upcoming",
  },
  {
    id: "11",
    name: "Billing Event 11",
    date: "2023-11-01",
    type: "subscription",
    amount: "600.00",
    created_by: "user6",
    users: ["user10", "user11"],
    status: "draft",
  },
  {
    id: "12",
    name: "Billing Event 12",
    date: "2023-12-01",
    type: "one-time",
    amount: "650.00",
    created_by: "user7",
    users: ["user12"],
    status: "completed",
  },
  {
    id: "13",
    name: "Billing Event 13",
    date: "2024-01-01",
    type: "subscription",
    amount: "700.00",
    created_by: "admin",
    users: "all",
    status: "cancelled",
  },
  {
    id: "14",
    name: "Billing Event 14",
    date: "2024-02-01",
    type: "one-time",
    amount: "750.00",
    created_by: "user8",
    users: ["user13", "user14"],
    status: "upcoming",
  },
  {
    id: "15",
    name: "Billing Event 15",
    date: "2024-03-01",
    type: "subscription",
    amount: "800.00",
    created_by: "user9",
    users: ["user15"],
    status: "draft",
  },
  {
    id: "16",
    name: "Billing Event 16",
    date: "2024-04-01",
    type: "one-time",
    amount: "850.00",
    created_by: "admin",
    users: "all",
    status: "completed",
  },
  {
    id: "17",
    name: "Billing Event 17",
    date: "2024-05-01",
    type: "subscription",
    amount: "900.00",
    created_by: "user10",
    users: ["user16", "user17"],
    status: "cancelled",
  },
  {
    id: "18",
    name: "Billing Event 18",
    date: "2024-06-01",
    type: "one-time",
    amount: "950.00",
    created_by: "user11",
    users: ["user18"],
    status: "upcoming",
  },
  {
    id: "19",
    name: "Billing Event 19",
    date: "2024-07-01",
    type: "subscription",
    amount: "1000.00",
    created_by: "admin",
    users: "all",
    status: "draft",
  },
  {
    id: "20",
    name: "Billing Event 20",
    date: "2024-08-01",
    type: "one-time",
    amount: "1050.00",
    created_by: "user12",
    users: ["user19", "user20"],
    status: "completed",
  },
];
