import type { Metadata } from "next";
import "../globals.css";
import { inter, league_spartan } from "../fonts";
import Mainheader from "../../components/Mainheader";
import Mainfooter from "../../components/Mainfooter";

export const metadata: Metadata = {
  title: "ICAN Surulere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}  ${league_spartan.variable}`}>
      <head>
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <body>
        <Mainheader />
        {children}
        <Mainfooter />
      </body>
    </html>
  );
}
